Repository virtual-ecosystem/Simple-Virtual-Ecosystem, pull requests merged in 2020-06, with the labels that each got.

#9 Created FirstScene And SecondScene classes to create a map
  src/sve/gui/sample/Animal.java
  src/sve/gui/sample/AnimalTemplate.java
  src/sve/gui/sample/Background.java
  src/sve/gui/sample/Block.java
  src/sve/gui/sample/BlockTemplate.java
  src/sve/gui/sample/FirstScene.java
  src/sve/gui/sample/GameDisplay.css
  src/sve/gui/sample/GuiScene.java
  src/sve/gui/sample/SecondScene.java
  src/sve/gui/sample/environmentConstants.java
  src/sve/gui/sample/helperMethods.java
  src/sve/gui/sample/images/64-cheetah.jpg
  src/sve/gui/sample/images/64-gazelle.jpg
  src/sve/gui/sample/images/cheetah1.png
  src/sve/gui/sample/images/cheetah2.png
  src/sve/gui/sample/images/img1.png
  src/sve/gui/sample/images/img2.png
  src/sve/gui/sample/images/img3.png
  src/sve/gui/sample/images/img4.png
  src/sve/gui/sample/images/img5.png
  src/sve/gui/sample/images/img_grass1.png
  src/sve/gui/sample/images/img_grass2.png
  src/sve/gui/sample/images/img_tree1.png
  src/sve/gui/sample/images/img_tree2.png
  src/sve/gui/sample/images/img_tree_small1.png
  src/sve/gui/sample/images/img_tree_small2.png
Labels: enhancement

#15 Added stubs for SVE in general
  src/sve/core/Animal.java
  src/sve/core/AnimalGenerator.java
  src/sve/core/Biome.java
  src/sve/core/BiomeGenerator.java
  src/sve/core/Block.java
  src/sve/core/Condition.java
  src/sve/core/Generator.java
  src/sve/core/LifePeriod.java
  src/sve/core/LifeTime.java
  src/sve/core/LivingBeing.java
  src/sve/core/Movable.java
  src/sve/core/Point1D.java
  src/sve/core/Point2D.java
  src/sve/core/Resource.java
  src/sve/core/ResourceType.java
  src/sve/core/RuntimeGenerator.java
  src/sve/core/Sex.java
  src/sve/gui/.gitkeep
  src/sve/gui/RenderTypes.java
  src/sve/gui/Renderable.java
  src/sve/stats/.gitkeep
  src/sve/stats/GraphType.java
  src/sve/stats/Graphicer.java
  src/sve/stats/Session.java
Labels: enhancement

#18 Created and designed some kind of gui
  src/sve/core/Cheetah.java
  src/sve/core/Gazelle.java
  src/sve/gui/AnimalCreator.java
  src/sve/gui/Background.java
  src/sve/gui/Block.java
  src/sve/gui/BlockTemplate.java
  src/sve/gui/FirstScene.java
  src/sve/gui/GameDisplay.css
  src/sve/gui/GuiScene.java
  src/sve/gui/OptionScene.java
  src/sve/gui/SecondScene.java
  src/sve/gui/StatsPopup.java
  src/sve/gui/Toast.java
  src/sve/gui/environmentConstants.java
  src/sve/gui/helperMethods.java
  src/sve/gui/images/64-cheetah.jpg
  src/sve/gui/images/64-gazelle.jpg
  src/sve/gui/images/cheetah1.png
  src/sve/gui/images/cheetah2.png
  src/sve/gui/images/img1.png
  src/sve/gui/images/img2.png
  src/sve/gui/images/img3.png
  src/sve/gui/images/img4.png
  src/sve/gui/images/img5.png
  src/sve/gui/images/img_grass1.png
  src/sve/gui/images/img_grass2.png
  src/sve/gui/images/img_tree1.png
  src/sve/gui/images/img_tree2.png
  src/sve/gui/images/img_tree_small1.png
  src/sve/gui/images/img_tree_small2.png
Labels: enhancement

#20 Fixed build system errors
  Makefile
  src/sve/gui/SecondScene.java
Labels: fix

#24 Added some charts to secondScene and Fixed some issues
  src/sve/event/EventType.java
  src/sve/gui/FirstScene.java
  src/sve/gui/GuiScene.java
  src/sve/gui/OptionScene.java
  src/sve/gui/SecondScene.java
  src/sve/gui/StatisticsTab.java
Labels: enhancement, fix
